### PR TITLE
AF-1511: consolidate kie-wb/kie-drools-wb into single business-central

### PR DESCRIPTION
**Pull request by jhrcek**
Changes in jenkins jobs required by the consolidation of kie-wb and kie-drools-wb into single business-central distribution.

Part of an ensemble:
https://github.com/kiegroup/kie-jenkins-scripts/pull/337
https://github.com/kiegroup/kie-wb-distributions/pull/815
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/834

### CODE REVIEW

**Comment by jhrcek** [comment]
@jesuino please check if the changes here correspond to your changes in kie-wb-distributions

**Comment by mbiarnes** [comment]
@jhrcek can you please also erase this dependency:
[kie-server-*ee6.war](https://github.com/kiegroup/kie-jenkins-scripts/blob/master/job-dsls/jobs/downstream_pr_jobs.groovy#L34)", - since we don't create this artifact anymore?
I know that this should have been removed before :)

**Comment by jhrcek** [comment]
@mbiarnes Sure, I added one more commit removing the ee6 distro of kie-server from archived artifacts. But let's not merge this yet before the situation with the merging of kie-wb wars is clarified in kie-wb-distributions..

**Comment by krisv** [comment]
Do NOT merge before any open items on https://issues.jboss.org/browse/BAPL-1080 are resolved.

**Comment by jhrcek** [comment]
Rebased onto master and resolved merge conflicts. @jesuino please check again, as it's been a long time since this PR was originally submitted.

**Pull request merged**
