### PR TITLE
BXMSPROD-1425 ghprbTrigger.excludedRegions

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1425

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

### CODE REVIEW

**Review by mbiarnes — APPROVED** [review]
+1

**Comment by mbiarnes** [comment]
@Ginxo Caused by: javaposse.jobdsl.dsl.DslScriptException: (script, line 279) No signature of method: java.lang.String.call() is applicable for argument types: (String) values: [[LICENSE.*, \.gitignore, .*\.md, .*\.adoc, .*\.txt]]
Possible solutions: wait(), any(), wait(long), split(java.lang.String), any(groovy.lang.Closure), tap(groovy.lang.Closure)

**Review by ricardozanini — APPROVED** [review]
Pretty nice! Many thanks for this, it will help a lot!

**Comment by Ginxo** [comment]
Jenkins retest this

**Review by ricardozanini — APPROVED** [review]

**Comment by mbiarnes** [comment]
@Ginxo can you plaese remove https://github.com/kiegroup/kie-jenkins-scripts/pull/1043/files#diff-14d947a618168d9120e666f243365a85919221e3d30de6071de4ce3fbbd0efbcL222 - we prevent to have the "main" branch displayed twice as white listed branches

**Pull request merged**
