### PR TITLE
[DROOLS-1521] Add DSL script for downstream PR jobs

### PR DESCRIPTION
**Pull request by psiroky**
@mbiarnes please take a look whenever you have some time

### CODE REVIEW

**Comment by mbiarnes** [comment]
@psiroky why are droolsjbpm-tools, kie-docs and kie-wb-distributions excluded?

**Comment by psiroky** [comment]
@mbiarnes because no other repos depend on them, so there is no downstream build required. I thought the comment explains that clearly, but maybe it could be enhanced.

**Comment by mbiarnes** [comment]
@psiroky well explained - it is more that I didn't understand this well, my personal groovy lack- I understood that these are the job to creates a build for each repostory when a PR is raised - so in my understanding (I repeat in my understanding and this could be wrong) I see that droolsjbpm-tools, kie-docs and kie-wb-distributions are excluded - so there is no PR-job for them? But for sure I don't see where all <reps> are defined   - I thought they are listed in REPO_CONFIGS

**Comment by psiroky** [comment]
@mbiarnes we already have "standard" PR jobs for all the repos. See https://github.com/kiegroup/kie-jenkins-scripts/blob/master/job-dsls/jobs/pr_jobs.groovy. These changes are a new set of jobs, which run the whole downstream build (not just the build for the repo for which the PR was created). For some repos it does not make sense to execute the downstream build, so those are excluded (actually commented right now, but we can remove them completely as well).

**Comment by psiroky** [comment]
@mbiarnes could you please check this again? Is there anything else I should update before merging?

**Comment by mbiarnes** [comment]
@psiroky looks good +1

**Pull request merged**
