### PR TITLE
Adds 8GB swap file.

### PR DESCRIPTION
**Pull request by pszubiak**
Signed-off-by: Piotr Szubiakowski <pszubiak@redhat.com>

### CODE REVIEW

**Comment by mareknovotny** [comment]
8GB swap and what is the memory size dedicated ? I don't recall if that was higher than 8GB.

**Comment by pszubiak** [comment]
It depends we have several templates:

ci-rhos-rhel7-large - 8 GB

ci-rhos-rhel7-medium - 4GB

ci-rhos-rhel7-xlarge - 24GB

**Comment by mareknovotny** [comment]
so for *xlarge that swap size would be not enough imho

**Comment by pszubiak** [comment]
Yep you can be right. I'm testing that now.

**Comment by AntStephenson** [comment]
8GB will probably be OK, but it'll be the _minimum_ we'd want to allocate.

**Pull request merged**
