### PR TITLE
increase JAVA mem

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
do not merge yet -
first we have to see if this works. the changes were done directly on Jenkins in: 
https://github.com/kiegroup/kie-wb-common/pull/3099
(logs: https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/kie-wb-common-downstream-pullrequests/714/console)
then we have to check if we want a increase to 8G for all compile downstreams - or only for kie-wb-common

**Comment by mbiarnes** [comment]
@romartin increased the mem to 16G (only for kie-wb-common) - for all other reps the mem will be 4G

**Comment by mbiarnes** [comment]
@romartin this is the one to look at: https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/kie-wb-common-downstream-pullrequests/717/console

**Comment by mbiarnes** [comment]
@romartin same error - so increase to 16G doesn't improve anything - thus I think the failure source is another

**Comment by romartin** [comment]
ok thanks @mbiarnes . I'll try to investigate again, although I think @manstis is also doing this, so plz guys be all on sync on this, if any updates let others know, I'll do!!! 
Thanks in advance!

**Comment by mbiarnes** [comment]
@romartin @mareknovotny 
increased PRs, FDB and CDB with MAVEN_OPTS -Xmx4g

**Comment by mareknovotny** [comment]
so is 4GB size enough? @romartin

**Pull request merged**
