### PR TITLE
[Don't merge] test tokens.

### PR DESCRIPTION
**Pull request by pszubiak**
Signed-off-by: Piotr Szubiakowski <pszubiak@redhat.com>

### CODE REVIEW

**Comment by kie-ci3** [comment]
test

**Comment by kie-ci4** [comment]
test

**Comment by kie-ci5** [comment]
test - kie-ci5

**Comment by kie-ci6** [comment]
test

**Comment by kie-ci7** [comment]
test

**Comment by kie-ci8** [comment]
test

**Comment by kie-ci9** [comment]
test

**Comment by kie-ci10** [comment]
test

**Comment by kie-ci2** [comment]
test

**Comment by kie-ci1** [comment]
test

**Pull request closed without merging**
