### PR TITLE
[KIECLOUD-600] - Remove RHDM from OSBS Seed Cloud Jobs

### PR DESCRIPTION
**Pull request by msmagnanijr**
See: https://issues.redhat.com/browse/KIECLOUD-600

Signed-off-by: Mauricio Magnani <msmagnanijr@gmail.com>

**Thank you for submitting this pull request**

**JIRA**:  Remove RHDM from OSBS Seed Cloud Jobs.

[link](https://issues.redhat.com/browse/KIECLOUD-600)

### CODE REVIEW

**Comment by msmagnanijr** [comment]
@jakubschwan @spolti just FYI

@Ginxo can you please approve and merge? thanks.

**Review by Ginxo — APPROVED** [review]
LGTM. Many thanks @msmagnanijr

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by msmagnanijr** [comment]
Jenkins retest this

**Comment by msmagnanijr** [comment]
@Ginxo the test failed but I think it is related to these constants [1] rather than my PR.

[1] - https://github.com/kiegroup/kie-jenkins-scripts/blob/main/job-dsls/src/main/groovy/org/kie/jenkins/jobdsl/Constants.groovy#L19

**Comment by Ginxo** [comment]
@mbiarnes @mwringe any idea about this `ERROR: No tool found matching KIE_JDK11_HOME_HOME` error, The double `_HOME` string seems weird to me... :thinking:

**Comment by mbiarnes** [comment]
I think this is green now. I observed this kind of error several times. But when you retest it disappears.

**Comment by mbiarnes** [comment]
@Ginxo this should fix the double HOME:
https://github.com/kiegroup/kie-jenkins-scripts/pull/1167

**Comment by msmagnanijr** [comment]
@mbiarnes @Ginxo could you please merge this? :)  thanks!

**Pull request merged**
