### PR TITLE
increased timeout for fdb

### PR DESCRIPTION
**Pull request by mbiarnes**
**Thank you for submitting this pull request**

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]

**Comment by tiagobento** [comment]
@caponetto FYI

**Comment by mareknovotny** [comment]
ok to test

@mbiarnes you have some issues with your account or why you now are not whitelisted on CI ? please look at that.

Btw add a description why we are increasing the limit. Is there now 10 hours enough for FDB?

**Comment by mareknovotny** [comment]
jenkins retest this

**Comment by mbiarnes** [comment]
@mareknovotny
@tiagobento and @caponetto  during testing their javadk11 stuff experienced a time out. They request it to increase:

`I believe we'll need to increase the FDB timeouts on Jenkins, since we noticed some FDBs are timing out. Me and @Guilherme Caponetto believe that 12h might be enough. Note that the FDBs we're running are not the standard use-case, since we're triggering them from `droolsjbpm-build-bootstrap` to compile and test the entire stack.`

**Comment by mbiarnes** [comment]
@mareknovotny this time out increase is only for the fdb(s) we have on Jenkins - not the build chain ones! This have toa be done one time they work.

**Comment by mareknovotny** [comment]
ok

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
