### PR TITLE
BXMSPROD-1061: DSL groovy script for rhba production full downstream build

### PR DESCRIPTION
**Pull request by mbiarnes**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[BXMSPROD-1061](https://issues.redhat.com/browse/BXMSPROD-1061)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* referenced pull request 1
* referenced pull request 2
* referenced pull request 2
etc. 

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

### CODE REVIEW

**Comment by mareknovotny** [comment]
could we have similar name for rhba_master as we have for community FDB?

**Comment by mbiarnes** [comment]
> could we have similar name for rhba_master as we have for community FDB?

@mareknovotny what do you mean? It creates a Jenkins job in KIE/master/downstream-production called rhba_master.fdbp

**Review by Ginxo — APPROVED** [review]
LGTM

**Comment by mareknovotny** [comment]
> > could we have similar name for rhba_master as we have for community FDB?
> 
> @mareknovotny what do you mean? It creates a Jenkins job in KIE/master/downstream-production called rhba_master.fdbp

I mean that community FDB job for master does have different name, while we should keep it similar name as this RHBA master is only prod FDB

**Review by Ginxo — COMMENTED** [review]
what if we copy/paste https://github.com/kiegroup/kie-jenkins-scripts/blob/c5a1f6f4e31392ee2cc1fe7f507202b871bc13ae/job-dsls/jobs/downstream_production.groovy replacing https://github.com/kiegroup/kie-jenkins-scripts/blob/c5a1f6f4e31392ee2cc1fe7f507202b871bc13ae/job-dsls/jobs/downstream_production.groovy#L58 by `String gitHubJenkinsfileRepUrl = "https://github.com/${ghOrgUnit}/rhba/"` (obivously `ghOrgUnit='jboss-integration'`) with one single project for the moment (RHBA).
WDYT?

**Comment by mbiarnes** [comment]
@mareknovotny @Ginxo changed name and made script extendible for more production projects

**Review by mareknovotny — APPROVED** [review]
now it looks ok

**Pull request merged**
