### PR TITLE
added new Maven version and removed 3.2 versions

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mareknovotny** [comment]
+1, @mbiarnes have you tried to use that extension upgraded to 3.6.0?

**Comment by mbiarnes** [comment]
> +1, @mbiarnes have you tried to use that extension upgraded to 3.6.0?

??? - how should this be tested

**Comment by mareknovotny** [comment]
@mbiarnes try to copy it to your local installation of maven 3.6.0 and do some builds ;)

**Comment by mbiarnes** [comment]
@mareknovotny tested with a mvn clean install and mvn clean deploy - and everything worked properly

**Comment by mbiarnes** [comment]
@mareknovotny when building kie-wb-commons with Maven 3.5.4 using this command
mvn clean install -Dfull -T1C -Dmaven.test.failure.ignore=true -Dgwt.memory.settings="-Xmx10g" the project builds, when using Maven 3.6.0 and the same command I get this [error](https://gist.github.com/mbiarnes/58fbef1815a4dfaebd6e303c9dc6f6ba)

**Comment by mareknovotny** [comment]
> @mareknovotny when building kie-wb-commons with Maven 3.5.4 using this command
> mvn clean install -Dfull -T1C -Dmaven.test.failure.ignore=true -Dgwt.memory.settings="-Xmx10g" the project builds, when using Maven 3.6.0 and the same command I get this [error](https://gist.github.com/mbiarnes/58fbef1815a4dfaebd6e303c9dc6f6ba)
where is the 3.6.0 version of jar tagged in that https://github.com/evanchsa/maven-parallel-resolver or any other fork?

**Comment by mbiarnes** [comment]
@mareknovotny ??? - I don't know where this version has to be tagged.

**Comment by mareknovotny** [comment]
@mbiarnes so where you got that jar?

**Comment by mbiarnes** [comment]
@mareknovotny I didn't kow that this jar has to be also in https://github.com/evanchsa/maven-parallel-resolver? I built it with this tool and the jar is in this PR. I thought this is enough

**Comment by mbiarnes** [comment]
$MAVEN_HOME/lib/ext locally

**Comment by mbiarnes** [comment]
@mareknovotny https://github.com/mbiarnes/maven-parallel-resolver/tree/3.6.0

**Pull request merged**
