### PR TITLE
added scripts for upgrade version of community kiegroup repositories

### PR DESCRIPTION
**Pull request by mbiarnes**
@mareknovotny these scripts are for automating the bump up of versions in all kiegroup community repositories & kie-benchmarks & kie-cloud-tests needed when a community release was done and all these versions have to be bumped up. Until now this was done manually. 

added script for upgrade version of kie-benchmarks

added script for upgrade version of kie-cloud-tests

added script for triggering all upgrade jobs

changed location and name of deploy_development_version

added upgrade jobs to  kie-tools seed-job

typo fixes

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[BXMSPROD-1535](https://issues.redhat.com/browse/BXMSPROD-1535)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* referenced pull request 1
* referenced pull request 2
* referenced pull request 2
etc. 

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

### CODE REVIEW

**Comment by mbiarnes** [comment]
@mareknovotny was tested here (against mbiarnes reps): https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/mbiarnes/job/KIE/job/kie-tools/job/upgradeVersions/

**Comment by mbiarnes** [comment]
@mareknovotny there is still missing one update: the update of kie prefix

**Comment by mbiarnes** [comment]
@mareknovotny @Ginxo 
the upgrade to a `next` version works for

- bumping up the versions (like after every community release)
- create new branches and bump up the versions (like after a community release when we branch i.e 7.59.x)

**Review by mareknovotny — COMMENTED** [review]
it looks fine. I have just formal complain that you don't stick to max 120 character long lines. How it is now is very hard to read it ;)

**Comment by mbiarnes** [comment]
> it looks fine. I have just formal complain that you don't stick to max 120 character long lines. How it is now is very hard to read it ;)

DONE

**Comment by mbiarnes** [comment]
Jenkins retest this

**Review by Ginxo — APPROVED** [review]
I'm ok with this change. I would just recommend to follow the same approach we are following for the new dsl pipeline jobs.
Like the one for https://github.com/kiegroup/kie-jenkins-scripts/blob/9bf4cedfcc3e0e337b06c7e27e3016c1320cf7b4/job-dsls/jobs/prod/prod_pr_jobs.groovy
storing the pipeline in an external file like https://github.com/kiegroup/kie-jenkins-scripts/blob/main/job-dsls/src/main/resources/job-scripts/prod_pr_jobs.jenkinsfile

This way it is much easier to read either the groovy script and the pipeline job and we don't have to scape $ or " or ' characters.

**Pull request merged**
