### PR TITLE
new 7.48.x branch

### PR DESCRIPTION
**Pull request by mbiarnes**
**Thank you for submitting this pull request**

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

### CODE REVIEW

**Comment by mbiarnes** [comment]
local failure: https://gist.github.com/mbiarnes/392da371dcc703ca9a30b20d654dfaac

**Comment by mbiarnes** [comment]
here it fails: https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/7.48.x/job/a-seed-job-7.48.x/2/console

**Review by mareknovotny — APPROVED** [review]
lgtm

**Review by Ginxo — APPROVED** [review]
LGTM

**Pull request merged**
