### PR TITLE
Bxmsprod 753 7.39.x

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by Ginxo** [comment]
@mbiarnes they need a different jobName or folde, otherwise they will collide with the master's ones
second thing, we should rebase https://github.com/kiegroup/kie-jenkins-scripts/pull/768 once it's merged

**Comment by mareknovotny** [comment]
don't they have different folder on Jenkins? @Ginxo

**Comment by mbiarnes** [comment]
@Ginxo the jobs (a-seed-job) for 7.39.x is in this folder KIE/7.39.x - so everything created will be created from KIE/7.39.x as root dir. So nothing will collide because the big difference here is master or 7.39.x. If you look now you will see the same folder in master or 7.39.x.

**Comment by mbiarnes** [comment]
@Ginxo the changes of the additionalArtifacts are the same as on master

**Pull request merged**
