### PR TITLE
[BXMSPROD-1339] - Changed to maven version 3.8.1

### PR DESCRIPTION
**Pull request by akoufoudakis**
**Thank you for submitting this pull request**

**JIRA**: _BXMSPROD-1339_ 

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* https://github.com/kiegroup/kie-jenkins-scripts/pull/1015

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

### CODE REVIEW

**Review by winklerm — APPROVED** [review]
Thanks!

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
btw we should also look for the .mvn folder definition with maven extensions, where is not required anymore? tagging @winklerm and @Ginxo

**Comment by Ginxo** [comment]
just consider thanks to https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1671/files it will be possible to choose maven tool per job.
@mareknovotny are you suggesting to remove .mvn folder from every repository? What about `--builder smart -T1C` from https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/2311c2c73b5929dda6166351d001b6f50566b90c/.ci/pull-request-config.yaml#L8

**Comment by mareknovotny** [comment]
> just consider thanks to https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1671/files it will be possible to choose maven tool per job.
> @mareknovotny are you suggesting to remove .mvn folder from every repository? 

nope

> What about `--builder smart -T1C` from https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/2311c2c73b5929dda6166351d001b6f50566b90c/.ci/pull-request-config.yaml#L8

we could only remove the extension command if that makes sense, but not sure if all extensions works fine with the latest maven

**Comment by Ginxo** [comment]
the maven version should be also consider on @mareknovotny  @akoufoudakis 
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/3e968a15ca77bb99d9a1538ba2c4d6f55063fd99/Jenkinsfile.buildchain#L70
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/3e968a15ca77bb99d9a1538ba2c4d6f55063fd99/Jenkinsfile.nightly#L8
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/3e968a15ca77bb99d9a1538ba2c4d6f55063fd99/Jenkinsfile.revapi#L17

**Pull request merged**
