### PR TITLE
added compile downstream build for appformer pull requests

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by baldimir** [comment]
I think it needs to be `if (repo != "drools") && (repo != appformer)`. Otherwise it will just go to the `if (repo != "drools")` code branch.

**Comment by mbiarnes** [comment]
@baldimir please let me know if 
this has to be backported to 7.1.4.x

**Comment by baldimir** [comment]
@porcelli @ederign any opinion please?

**Comment by jhrcek** [comment]
@ederign 
current status: 
- regular PR build (just 1 repo, running tests) executed automatically
- full downstream build executed only on demand

after this PR
- one extra job executed automatically (full compile downstream).

This compile downstream job was introduced after the request of drools team, because it happened several times, that their changes broke downstream repos (e.g. drools-wb). Recently it happened, that a change in appformer broke something in the downstream repos too, so @baldimir suggested should consider having this job too (but it's up to us to decide if we find value in it or not).

**Comment by baldimir** [comment]
To clarify more - compile downstream is not full downstream build. It compiles the downstream repositories, without running tests. It serves as a compilation check (not a runtime check).

**Comment by ederign** [comment]
@jhrcek @baldimir so after this PR we still have:

- regular PR build (just 1 repo, running tests) executed automatically for all repos
- full downstream build executed only on demand for all repos
- full compile downstream build (all repos, no tests, no gwt compilation etc, just java compilation) executed automatically for drools only, for other repos only on demand.

and also:
- compile downstream executed automatically?

**Comment by baldimir** [comment]
@ederign this PR is about running compile downstream build automatically for all Appformer PRs. So you would have a regular PR check and an additional compile downstream check on all Appformer PRs.

**Pull request merged**
