### PR TITLE
repeatable step

### PR DESCRIPTION
**Pull request by mbiarnes**
**Thank you for submitting this pull request**

in case the pull of tags to Gerrit  fails because whatever reason the pipeline will "halt", fixes can be done and the step re-tried . the pipeline  continues.

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

### CODE REVIEW

**Review by winklerm — COMMENTED** [review]
Just wondering, could you use [1]?

[1] https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#retry-retry-the-body-up-to-n-times

**Comment by mbiarnes** [comment]
> Just wondering, could you use [1]?
> @winklerm 
> [1] https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#retry-retry-the-body-up-to-n-times
I saw in kogito pipelines and community pipelines this is working

**Review by Ginxo — CHANGES_REQUESTED** [review]
I would use https://github.com/kiegroup/jenkins-pipeline-shared-libraries/blob/be6131c868dbc35b664595aab3d3d2f89b918944/vars/PipelineHelper.groovy#L11 instead
```
new PipelineHelper().retry(
{
echo 'Name of the tag: ' + "$tagName"
sshagent(['code.engineering.redhat.com']) {
sh './droolsjbpm-build-bootstrap/script/release/08b_prodPushTags.sh $tagName'
} ,  X, Y, {
        input "Retry step?"
        retry++
        echo "This is retry number ${retry}"
        execute(closure)
    } )
```
(replace X and Y) and remove `void execute` from #L187

**Comment by mbiarnes** [comment]
@Ginxo @winklerm tried to introduce changes mentioned by Enrique, but this doesn't work 100% - I re-edited the first approach and this was tested

**Pull request merged**
