### PR TITLE
jdk17 added to kie-rhel machine

### PR DESCRIPTION
**Pull request by Ginxo**
<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

### CODE REVIEW

**Comment by Ginxo** [comment]
waiting for ansible testing

**Review by radtriste — APPROVED** [review]

**Review by mareknovotny — COMMENTED** [review]
lgtm

**Comment by Ginxo** [comment]
The test is working https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/Tools/job/agent-image-build-PR-test/9/console

**Review by winklerm — APPROVED** [review]
Thanks!

**Pull request merged**
