### PR TITLE
kie-server-tests need a 'wildfly10x' profile

### PR DESCRIPTION
**Pull request by psiroky**
cc @sutaakar

### CODE REVIEW

**Comment by sutaakar** [comment]
@psiroky Would it have more sense to unify it? It may prevent such issues in future.

**Comment by psiroky** [comment]
@sutaakar it has been unified on 7.x+ branches. I can do the same here, but did not want to disrupt the current job configs. If its fine with you, I'll do it.

**Comment by sutaakar** [comment]
@psiroky From QE point it is ok, it won't make any problem.

**Comment by psiroky** [comment]
@sutaakar great, thanks. I'll rename the profile to `wildfly10`.

**Comment by sutaakar** [comment]
@psiroky Please rename also other profiles, to keep them consistent.

**Comment by psiroky** [comment]
See https://github.com/kiegroup/droolsjbpm-integration/pull/1156. I am closing this one as after that PR gets merged, these changes won't be needed.

**Pull request closed without merging**
