### PR TITLE
update new_pr_jobs.groovy default artifactToArchive removed

### PR DESCRIPTION
**Pull request by Ginxo**

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by mbiarnes** [comment]
@Ginxo I don't know why this doesn't work - it should

**Comment by Ginxo** [comment]
Jenkins retest this please

**Comment by Ginxo** [comment]
@mbiarnes artifactsToArchive is needed by the script (otherwise we would have to modify script and it's better to leave as the rest of its kind). Added and working

**Pull request merged**
