### PR TITLE
[BXMSPROD-402] - Create seed job for cloud image builds

### PR DESCRIPTION
**Pull request by msmagnanijr**
See: https://issues.jboss.org/browse/BXMSPROD-402

Signed-off-by: Mauricio Magnani <mmagnani@redhat.com>

### CODE REVIEW

**Comment by mareknovotny** [comment]
There is still some problem with a property

```
org.kie.jenkins.jobdsl.JobScriptsSpec > test script seed_job_cloud.groovy FAILED
    org.spockframework.runtime.UnallowedExceptionThrownError at JobScriptsSpec.groovy:47
        Caused by: javaposse.jobdsl.dsl.DslScriptException at JobScriptsSpec.groovy:43
            Caused by: groovy.lang.MissingPropertyException at JobScriptsSpec.groovy:43
```

**Comment by mareknovotny** [comment]
there is still CI job error, can you @msmagnanijr fix that ? 

```
Expected no exception to be thrown, but got 'javaposse.jobdsl.dsl.DslScriptException'
	at spock.lang.Specification.noExceptionThrown(Specification.java:118)
	at org.kie.jenkins.jobdsl.JobScriptsSpec.test script #file.name(JobScriptsSpec.groovy:47)
Caused by: javaposse.jobdsl.dsl.DslScriptException: (script, line 15) No such property: BUILD_DATE for class: javaposse.jobdsl.dsl.helpers.BuildParametersContext
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScriptEngine(AbstractDslScriptLoader.groovy:111)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScripts_closure1(AbstractDslScriptLoader.groovy:60)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScripts(AbstractDslScriptLoader.groovy:46)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScript(AbstractDslScriptLoader.groovy:85)
	at org.kie.jenkins.jobdsl.JobScriptsSpec.test script #file.name(JobScriptsSpec.groovy:43)
Caused by: groovy.lang.MissingPropertyException: No such property: BUILD_DATE for class: javaposse.jobdsl.dsl.helpers.BuildParametersContext
	at script$_run_closure1.closure2$_closure3(script:15)
	at script$_run_closure1.closure2$_closure3(script)
	at javaposse.jobdsl.dsl.ContextHelper.executeInContext(ContextHelper.groovy:16)
	at javaposse.jobdsl.dsl.Job.parameters(Job.groovy:510)
	at script.run_closure1$_closure2(script:14)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at javaposse.jobdsl.dsl.JobParent.processItem(JobParent.groovy:115)
	at javaposse.jobdsl.dsl.JobParent.pipelineJob(JobParent.groovy:97)
	at script.run_closure1(script:12)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:430)
	at script.run(script:10)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScript(AbstractDslScriptLoader.groovy:132)
	at javaposse.jobdsl.dsl.AbstractDslScriptLoader.runScriptEngine(AbstractDslScriptLoader.groovy:105)
	... 6 more
```

**Comment by mbiarnes** [comment]
@msmagnanijr @jakubschwan 
looking at the error I would suggest:
insert `import org.kie.jenkins.jobdsl.Constants`
add a `def` for all parameters (fetched from the Contsants.properties) - i.e. like https://github.com/kiegroup/kie-jenkins-scripts/blob/master/job-dsls/jobs/dailyBuild_pipeline.groovy#L10

**Comment by mareknovotny** [comment]
@mmagnanijr you still need to complete the advice from @mbiarnes ;) The import is not enough

> add a def for all parameters (fetched from the Contsants.properties) - i.e. like https://github.com/kiegroup/kie-jenkins-scripts/blob/master/job-dsls/jobs/dailyBuild_pipeline.groovy#L10

**Comment by msmagnanijr** [comment]
> @mmagnanijr you still need to complete the advice from @mbiarnes ;) The import is not enough
> 
> > add a def for all parameters (fetched from the Contsants.properties) - i.e. like https://github.com/kiegroup/kie-jenkins-scripts/blob/master/job-dsls/jobs/dailyBuild_pipeline.groovy#L10

Done! thank you for the tips. It's a little hard to test this out of Jenkins before pushing.

**Pull request merged**
