### PR TITLE
Fix trigger string to accept more loosely based requests.

### PR DESCRIPTION
**Pull request by AntStephenson**
Fix the trigger string to more accepting, for example "jenkins retest please" as seen in: 
https://github.com/kiegroup/kogito-examples/pull/685

### CODE REVIEW

**Review by mbiarnes — APPROVED** [review]
LGTM

**Comment by mareknovotny** [comment]
thanks @AntStephenson we probably need to update also PR template now in https://github.com/kiegroup/droolsjbpm-build-bootstrap/blob/master/.github/pull_request_template.md

**Comment by AntStephenson** [comment]
@mareknovotny What would you prefer to have there? I intentionally didn't update it since "Jenkins retest this" should probably still be the go-to, this just covers those edge cases I guess. if you have suggestions I can make the change.

**Comment by mareknovotny** [comment]
I just would update it as 'this' is not required anymore, but it is true it is not mandatory as it would work even with this

**Comment by AntStephenson** [comment]
Jenkins retest this

**Review by mareknovotny — APPROVED** [review]

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Pull request merged**
