### PR TITLE
BXMSPROD-1089: configure docker registry-mirror to internal cache

### PR DESCRIPTION
**Pull request by winklerm**
Update Jenkins agent images to configure Docker daemon registry-mirror option pointing to the local registry configured as a pull-through cache for Docker Hub.

**JIRA**:  [https://issues.redhat.com/browse/BXMSPROD-1089](BXMSPROD-1089)

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

### CODE REVIEW

**Review by mbiarnes — APPROVED** [review]
+1 LGTM

**Comment by winklerm** [comment]
Tested on Jenkins, seems that the mirror is configured but the original GitHib API rate limit problem is still not solved completely, we agreed to try a more recent version of docker/podman, so we are going to try upgrade KIE images to RHEL 8.

Nevertheless, I would propose merging this PR as it configures the mirror and do the RHEL upgrade in another PR.

**Review by mbiarnes — APPROVED** [review]
+1

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by winklerm** [comment]
Tested on Jenkins, after Docker upgrade to a recent version, the test job runs successfully.

**Comment by winklerm** [comment]
Waiting for final confirmation by Mauricio.

**Comment by msmagnanijr** [comment]
> Waiting for final confirmation by Mauricio.

lgtm!

**Comment by winklerm** [comment]
Fixed the podman config, thanks to @Kaitou786 !

**Comment by winklerm** [comment]
Even quarkus-maven-plugin seems to be working now after @cristianonicolai 's changes, I would suggest waiting for confirmation tomorrow and then merge this PR.

**Comment by winklerm** [comment]
Jenkins retest this

**Comment by winklerm** [comment]
I believe we can merge this PR now.

**Pull request merged**
