### PR TITLE
removed jobs for kie-soup, uberfire and dashbuilder

### PR DESCRIPTION
**Pull request by mbiarnes**
@psiroky can you please merge (once green) - I want to do a test-release

### CODE REVIEW

**Comment by psiroky** [comment]
@mbiarnes is this somehow related to the two PRs Max created? https://github.com/kiegroup/kie-jenkins-scripts/pull/112 and https://github.com/kiegroup/kie-jenkins-scripts/pull/111

**Comment by mbiarnes** [comment]
@psiroky nop - because the files changed we for the releases. not for dailyBuilds - these files are for the dailyBuild jobs

**Comment by psiroky** [comment]
I don't understand -- do all the PRs need to be merged together?

**Comment by mbiarnes** [comment]
this PR here is "standalone" - if you merge we will see if the dailyBuild works

**Comment by mbiarnes** [comment]
@psiroky this will change only job-dsls/jobs/FlowJob.groovy - nothing more .

**Pull request merged**
