### PR TITLE
BXMSPROD-1036: added deploy jobs for opta* 7.x

### PR DESCRIPTION
**Pull request by mbiarnes**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://examle.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* referenced pull request 1
* referenced pull request 2
* referenced pull request 2
etc. 

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

### CODE REVIEW

**Comment by mbiarnes** [comment]
added new deploy jobs for optaplanner 7.x branch as well as optaweb 7.x branches,
thus we have a deploy jobs for master and for 7.x branches, depending which PRs are merged

**Comment by mbiarnes** [comment]
IMPORTANT: thsi PR should be merged before #828 since the seed job was changed already online. The seed-jobs expects                     deploy_jobs_7_x.groovy!

**Comment by mareknovotny** [comment]
Doesn't that removal of 7.x branch create now deploy job for optaplanner and optaweb repos also jobs for master branches? I think that is not what we want, I think

**Comment by rsynek** [comment]
@mbiarnes the deploy job for the master branch runs on Java 8, which won't work. OptaPlanner has already dropped Java 8, which is the main reason why I introduced the custom PR pipelines yesterday.

**Comment by mbiarnes** [comment]
@mareknovotny @rsynek will close this and open a new one

**Pull request closed without merging**
