### PR TITLE
added new script and adapt kie_releases_jobs.groovy to use the right …

### PR DESCRIPTION
**Pull request by mbiarnes**
…branches for master
@psiroky when someone merges this new script we should disable the Trigger kieAll for master to prevent that we have the execution twice. 
I would suggest we wait with the disabling until tomorrow so we can see if the new script works.

### CODE REVIEW

**Comment by mbiarnes** [comment]
@psiroky can you approve and merge it?

**Comment by psiroky** [comment]
@mbiarnes how urgent is it? There seems some duplication we could get rid of, but that would take some time to review. If its needed now, I will just merge it as is.

**Comment by mbiarnes** [comment]
@psiroky better to have everything working by DSL scripts then by parts - I want to replace the kieAll build master with this. I know well that there are a bunch of things we can get rid of in future

**Comment by psiroky** [comment]
Yeah, I am just afraid that once it gets merged it will never get fixed...but let's hope it will.

**Pull request merged**
