### PR TITLE
BXMSPROD-1468: switch all jobs to JDK 11

### PR DESCRIPTION
**Pull request by mbiarnes**
**Thank you for submitting this pull request**

**JIRA**: [BXMSPROD-1468](https://issues.redhat.com/browse/BXMSPROD-1468) 

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins test this

**Review by almope — APPROVED** [review]

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by almope** [comment]
jenkins test this

**Pull request merged**
