### PR TITLE
Add release script master

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
@psiroky 
this script works only if https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/438 was merged

**Comment by psiroky** [comment]
@mbiarnes ok, I'll take at the PRs asap.

**Comment by mbiarnes** [comment]
@psiroky can you please look at the test that failed?

**Comment by psiroky** [comment]
@mbiarnes I think you should take look at it since you are proposing the changes :)

**Comment by mbiarnes** [comment]
@psiroky I did ./gradlew clean test locally and it states:
Caused by: javaposse.jobdsl.dsl.DslScriptException: (script, line 125) plugin 'toolenv' needs to be installed
I use toolenv. I run this script several time on Jenkins CI (for testing) and I had no problems.
As I can see we have a [Tool Environment plugin](http://wiki.hudson-ci.org/display/HUDSON/Tool+Environment+Plugin) installed. Tbh I don't know if we need a new plugin?

**Comment by psiroky** [comment]
@mbiarnes the plugin needs to added here https://github.com/kiegroup/kie-jenkins-scripts/blob/master/job-dsls/build.gradle#L49 so that it's present during the test execution.

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by mbiarnes** [comment]
@psiroky all done

**Comment by mbiarnes** [comment]
@psiroky can you merge this please as we need this on Tuesday for the new 7.1.x branch or the resultant branch of master when we release the 7.1.0.Final

**Pull request merged**
