### PR TITLE
KOGITO-4767 - Upgrade GraalVM to version 20.3.1.2

### PR DESCRIPTION
**Pull request by cristianonicolai**
**Thank you for submitting this pull request**

**JIRA**: 

[KOGITO-4767](https://issues.redhat.com/browse/KOGITO-4767)

**referenced Pull Requests**: 

* https://github.com/kiegroup/kogito-runtimes/pull/1168

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
is @radtriste comment on kiegroup/kogito-runtimes#1168 complementary or it can be done without this change?

**Comment by radtriste** [comment]
about https://github.com/kiegroup/kogito-runtimes/pull/1168#issuecomment-804941537complementary, this is to be able to build native without having to change the GraalVM version each time on the node. We can use directly the docker image containing the GraalVM. 
That change is not mandatory once all PRs from https://issues.redhat.com/browse/KOGITO-4770 are merged.
But it is always good also to keep up to date. 

As we are working on Quarkus 1.11, GraalVM 20.3+ is the one to set.
Note that once we update to Quarkus 1.12, GraalVM 21.0+ will be mandatory.

**Comment by radtriste** [comment]
But as I said, GraalVM is needed for native compilation only and we can workaround by using the docker image: https://quarkus.io/guides/building-native-image#container-runtime

**Comment by mareknovotny** [comment]
I am ok with updating regularly @cristianonicolai @radtriste, but that means there is a testing phase to try new build node image every time we merge this upgrade and after that change the label for new build node image. This is not free and occupy time someone else as it needs to be done manually  cc @winklerm @mbiarnes

**Comment by radtriste** [comment]
Then I would say that we need to determine if GraalVM is really mandatory on the node as it could cause more maintenance.
The workaround by using [docker images](https://quarkus.io/guides/building-native-image#container-runtime) is working well on Kogito pipelines. It works as long as you are using Quarkus.

**Review by mbiarnes — APPROVED** [review]
LGTM

**Pull request merged**
