### PR TITLE
changed daily builds kie prefix to 7.55.0

### PR DESCRIPTION
**Pull request by mbiarnes**
**Thank you for submitting this pull request**

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins retest this

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
no CI check trigger working?

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Pull request merged**
