### PR TITLE
PLANNER-2467 Jenkinsfiles moved to .ci/jenkins

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

**JIRA**: https://issues.redhat.com/browse/PLANNER-2467

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1025
* https://github.com/jboss-integration/rhba/pull/42
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1688

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

### CODE REVIEW

**Comment by Ginxo** [comment]
@almope @mbiarnes can you please review https://github.com/jboss-integration/rhba/pull/42 aswell

**Review by almope — APPROVED** [review]

**Review by mbiarnes — APPROVED** [review]
+1

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by Ginxo** [comment]
@mbiarnes this one can't be merged without the related PRs, otherwise we break CI... Let's see if we can merge them

**Pull request merged**
