### PR TITLE
remove jobs that are not anymore built via dsl

### PR DESCRIPTION
**Pull request by mbiarnes**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://examle.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* referenced pull request 1
* referenced pull request 2
* referenced pull request 2
etc. 

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Comment by mbiarnes** [comment]
@winklerm @Ginxo @rgdoliveira @lampajr 
there are also seed jobs for 
OSBS: https://github.com/kiegroup/kie-jenkins-scripts/blob/main/job-dsls/jobs/seed_jobs/osbs_seed_job.groovy
PROD: https://github.com/kiegroup/kie-jenkins-scripts/blob/main/job-dsls/jobs/seed_jobs/prod_seed_job.groovy
should the parameter `removedJobAction` also be set to DELETE 
removedJobAction = Specifies what to do when a previously generated job is not referenced anymore.
Note: when using multiple Job DSL build steps in a single job, set this to "Delete" or "Disable" only for the last Job DSL build step. Otherwise jobs will be deleted and re-created or disabled and re-enabled and you may lose the job history of generated jobs. See [JENKINS-44142](https://issues.jenkins-ci.org/browse/JENKINS-44142) for details.

**Review by winklerm — APPROVED** [review]
If you are sure that the target folders do not contain any non-JobDSL-templated jobs, then it looks good to me :)

**Review by Ginxo — APPROVED** [review]
LGTM

**Comment by radtriste** [comment]
> If you are sure that the target folders do not contain any non-JobDSL-templated jobs, then it looks good to me :)

The problem would happen only if the jobDSL end up deleting a complete folder.
All other jobs which were not generated/managed by the seed job are left untouched and won't be deleted

**Review by lampajr — APPROVED** [review]

**Pull request merged**
