### PR TITLE
BXMSPROD-1478 Update Operator-sdk/Golang versions

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/BXMSPROD-1478

Follow-up on https://github.com/kiegroup/kogito-operator/pull/995

- Golang version will be available as a [tool](https://plugins.jenkins.io/golang/#documentation)
- Operator-sdk will be installed by operator scripts: https://github.com/kiegroup/kogito-operator/pull/1024

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

### CODE REVIEW

**Comment by radtriste** [comment]
jenkins retest this

**Review by winklerm — APPROVED** [review]
LGTM, thanks! Just checking, the `GOROOT=/opt/tools/golang/1.16/go` is hardcoded to 1.16 intentionally, correct (I guess we just want the newer version there and handle it using golang plugin in the jobs)?

**Comment by radtriste** [comment]
yes we want the last version of golang as default, always

**Comment by radtriste** [comment]
works like a charm

**Pull request merged**
