### PR TITLE
[BXMSPROD-1558] @kie scope added

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

https://issues.redhat.com/browse/BXMSPROD-1558

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* https://github.com/kiegroup/lock-treatment-tool/pull/1

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

### CODE REVIEW

**Review by jomarko — APPROVED** [review]
Approving this part of ensemble, to be able  relaunch other jobs using this `.npmrc` at proper location.

**Review by winklerm — APPROVED** [review]

**Review by mbiarnes — APPROVED** [review]
LGTM

**Review by mareknovotny — APPROVED** [review]

**Comment by Ginxo** [comment]
tested by https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/Tools/job/Images/job/agent-image-build-PR-test/1/

**Comment by Ginxo** [comment]
I guess it won't be needed after https://github.com/kiegroup/lock-treatment-tool/pull/3
Testing it

**Comment by Ginxo** [comment]
tested and working by https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-editors-java.tests.kogito-tooling-editors-java/345/console

**Pull request merged**
