### PR TITLE
changed default version name to XXX.BetaX

### PR DESCRIPTION
**Pull request by mbiarnes**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://examle.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* referenced pull request 1
* referenced pull request 2
* referenced pull request 2
etc. 

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

### CODE REVIEW

**Comment by mareknovotny** [comment]
I think this change is not needed, nonetheless what the version will be, why we need to guide the specific version here, you still can fill whatever you want or not?

**Comment by mbiarnes** [comment]
> I think this change is not needed, nonetheless what the version will be, why we need to guide the specific version here, you still can fill whatever you want or not?

hmm - I think it is better for who ever does this release he has an example of how to call the version. There were so many complains about the t<date> version extension.

**Comment by mareknovotny** [comment]
there were only complaints from @ge0ffrey but it was related to Optaplanner which we removed from the list of such releases.

**Comment by mbiarnes** [comment]
> there were only complaints from @ge0ffrey but it was related to Optaplanner which we removed from the list of such releases.

up to you - if you find this change not needed feel free to close this - but look first on changes I have also done to the doc: 
https://repository.jboss.org/nexus/content/groups/public/org/drools/drools-bom/7.46.0.Beta1/

**Pull request closed without merging**
